apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-portal-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-portal
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-portal
    helm:
      values: |2-
        glooEdge:
          enabled: true
        licenseKey:
          secretRef:
            name: license
            namespace: gloo-system
            key: license-key
    repoURL: https://storage.googleapis.com/dev-portal-helm
    targetRevision: 1.2.0-beta4
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
      - CreateNamespace=true