apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

namespace: argocd

patchesJson6902:
- path: overlays/argocd-server-insecure-rootpath.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1
- path: overlays/argocd-redis-uid-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-redis
    version: v1