{{- if .Values.controlPlane.enabled -}}
{{- if .Values.controlPlane.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gloo-gateway.controlPlane.serviceAccountName" . }}
  labels:
    {{- include "gloo-gateway.gateway.const_labels" . | nindent 4 }}
    {{- include "gloo-gateway.controlPlane.labels" . | nindent 4 }}
  {{- with .Values.controlPlane.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}