apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-portal-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-portal
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-portal
    helm:
      values: |
        glooEdge:
          enabled: true
        istio:
          enabled: false
        glooMesh:
          enabled: false
        licenseKey: 
          value: eyJleHAiOjE2NzI2MDc0NjksImlhdCI6MTYyNTc3ODY2OSwiayI6IlY4T044dyIsImx0IjoidHJpYWwiLCJwcm9kdWN0IjoiZ2xvbyJ9.IiS_yno2_YHR7xSOT2z0BcbCzsY0Bb1ESHt1nJcEAJE
    repoURL: https://storage.googleapis.com/dev-portal-helm
    targetRevision: 1.1.2
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
      - CreateNamespace=true