##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  labels:
    account: productpage
