apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge-oss
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo
    helm:
      values: |
        # no values takes the default values.yaml
    repoURL: https://storage.googleapis.com/solo-public-helm
    targetRevision: 1.8.25
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
      - CreateNamespace=true
