##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  labels:
    account: reviews