apiVersion: security.policy.gloo.solo.io/v2
kind: WAFPolicy
metadata:
  name: httpbin-log4shell
  namespace: httpbin
spec:
  applyToRoutes:
  - route:
      labels:
        waf: "true"
  config:
    customInterventionMessage: Log4Shell malicious payload
    customRuleSets:
    - ruleStr: "SecRuleEngine On\nSecRequestBodyAccess On\nSecRule REQUEST_LINE|ARGS|ARGS_NAMES|REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_BODY|REQUEST_HEADERS|XML:/*|XML://@*
        \ \n  \"@rx \\${jndi:(?:ldaps?|iiop|dns|rmi)://\" \n  \"id:1000,phase:2,deny,status:403,log,msg:'Potential
        Remote Command Execution: Log4j CVE-2021-44228'\""
    disableCoreRuleSet: true