apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
data:
  # Number of application status processors (default 20)
  controller.status.processors: "60"
  # Number of application operation processors (default 10)
  controller.operation.processors: "60"
  # Repo server RPC call timeout seconds.
  controller.repo.server.timeout.seconds: "360"